# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.66.0"

default_platform :ios


platform :ios do
 
 desc "Creating a code signing certificate and provisioning profile"

 lane :provision do
    produce(
        app_name: 'mZone-digitaljavelina',
        language: 'English',
        app_version: '1.0',
        sku: '123abcxyz'
      )

    cert

    sigh(force: true)
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  error do |lane, exception|
    # This block is called if there was an error running a specific lane.
  end
end

